title: Janelle Williams
#logo: <img width="324" height="324" alt="Image" src="https://github.com/user-attachments/assets/ee991e7f-a5de-4adf-a728-b211d91bfe85"/>
description: Data Analyst
#show_downlaods: true
theme: jekyll-theme-minimal
